### ISSUE TITLE
Listener hooking question

### ISSUE THREAD

**Issue by UnlimitedNinjas** [DanJesensky/LagMeter#10]
link to the plugin i use: https://dev.bukkit.org/projects/lagmeter/pages/api
Server tps drops to 13 nothing. 
Heres the event:
https://pastebin.com/Lb2T6vXd

and is there a way to modify at what tps and mem % the events activate?

**Comment by TheLunarFrog** [comment]
Have you registered the listeners you're trying to hook ([asynchronous tps](https://github.com/TheLunarFrog/LagMeter/blob/master/main/java/com/webkonsept/minecraft/lagmeter/LagMeter.java#L1094), [asynchronous memory](https://github.com/TheLunarFrog/LagMeter/blob/master/main/java/com/webkonsept/minecraft/lagmeter/LagMeter.java#L1115]), [synchronous tps](https://github.com/TheLunarFrog/LagMeter/blob/master/main/java/com/webkonsept/minecraft/lagmeter/LagMeter.java#L1136), or [synchronous memory](https://github.com/TheLunarFrog/LagMeter/blob/master/main/java/com/webkonsept/minecraft/lagmeter/LagMeter.java#L1158))?

The thresholds are in the configuration ([tps](https://github.com/TheLunarFrog/LagMeter/blob/master/main/resources/settings.yml#L98), [memory](https://github.com/TheLunarFrog/LagMeter/blob/master/main/resources/settings.yml#L111) - note that the memory threshold is % free).

**Comment by UnlimitedNinjas** [comment]
i have this in on enable:
Bukkit.getServer().getPluginManager().registerEvents(this, this);
and i just added @EventHandler above them,  ill test it and let you know.
Also about the thresgolds i only found the mem one i cant find the tps one

**Comment by TheLunarFrog** [comment]
They are not Bukkit events, so you can't register them with Bukkit (as I would have no way of getting them from Bukkit). You have to get the LagMeter plugin from Bukkit, cast it to a LagMeter instance, then call the registration methods on that resulting instance.

Also be aware that your methods must be either lambda expressions or methods in a class that implement `com.webkonsept.minecraft.lagmeter.listeners.LagListener` or `com.webkonsept.minecraft.lagmeter.listeners.MemoryListener`.

Here is an example of something that could go in your onEnable:

```
LagMeter lm = (LagMeter)Bukkit.getPluginManager().getPlugin("LagMeter");
lm.registerAsyncLagListener(new MyHighLagListener());
```

Or if you're doing everything in one class (though not a good idea), you'd replace `new MyHighLagListener()` with `this`

**Comment by UnlimitedNinjas** [comment]
Okay so i aded this, and replace it with "this" since my events are in the main class
https://pastebin.com/4kaRxMre
still doesnt work, do i have to add some special @event above the events?

**Comment by TheLunarFrog** [comment]
Please show me how your class is defined.

**Comment by UnlimitedNinjas** [comment]
Here is my whole main class
https://pastebin.com/F5x5DpCj
i dont know what else i need?

**Comment by TheLunarFrog** [comment]
Sorry I haven't responded, I never got an email notification for some reason. Also been busy with work.

This should fix it:

https://pastebin.com/ugyixFnX

Note that I assumed your memory listener should also be async, like your tps listener.

Your listener class has to implement the listener type, so adding `LagListener` and `MemoryListener` to your `implements` clause is enough to fix the issue: `public class Main extends JavaPlugin implements Listener, CommandExecutor, LagListener, MemoryListener {`

Note that you no longer need the cast to `LagListener` for `this` in this case, as `this` is an instance of `LagListener`. Same for the memory one, which you hadn't registered yet. I added the registration in the paste above, but if you're not going to paste over your entire file, make sure you copy that part too. It's next to where you added the lag listener.

**Comment by UnlimitedNinjas** [comment]
No problem! School started and i cant be on, when i do i will try this. For now i will leave it here. 
Thanks for the help!
You can close this ticket if you would like.

**Comment by UnlimitedNinjas** [comment]
Thanks alot!!!! <3 I have had so much truble with getting this to work, i got the chance to test this and it works, thanks again <3. Your plugin is awesome, keep up the good work!!

**Comment by DanJesensky** [comment]
Glad you got it working! If you need any more help, let me know.
